# Generated by Django 5.2.5 on 2025-08-13 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_applicantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_image', models.ImageField(default='employer_default.png', upload_to='employerprofile/')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(default='company_logo.png', upload_to='companylogo/')),
                ('company_website_url', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField()),
                ('company_location', models.CharField(max_length=200)),
                ('employer_email', models.EmailField(max_length=254)),
                ('employer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('company_startdate', models.DateField(blank=True, null=True)),
                ('company_linkedin', models.URLField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
