# Generated by Django 5.2.5 on 2025-08-25 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(default='We are a growing company dedicated to excellence.'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/company/example', null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_location',
            field=models.CharField(default='Chennai, Tamil Nadu', max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default='xyz company', max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, default='11-50 employees', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_startdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website_url',
            field=models.URLField(blank=True, default='https://www.example.com', null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_contact',
            field=models.CharField(blank=True, default='+91-9876543211', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_email',
            field=models.EmailField(default='hr@example.com', max_length=254),
        ),
    ]
